# Generated by Django 5.1.3 on 2024-11-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_tg_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=255)),
                ('total_points', models.IntegerField()),
            ],
        ),
    ]
