# Generated by Django 5.1.3 on 2024-11-16 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banani_clicker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
    ]
