# Generated by Django 5.1.3 on 2024-11-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banani_clicker', '0002_rename_user_id_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_picture',
            field=models.ImageField(default='static/img/воладжон.jpg', upload_to='user_picture'),
        ),
    ]
