# Generated by Django 5.1.3 on 2024-11-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banani_clicker', '0003_user_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_picture',
            field=models.CharField(max_length=255),
        ),
    ]
