# Generated by Django 5.1.3 on 2024-11-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banani_clicker', '0004_alter_user_user_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardHoldings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('card_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('card_name', models.CharField(max_length=255)),
                ('card_cost', models.IntegerField()),
                ('card_add_points', models.IntegerField()),
                ('card_rarity', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='coins_per_sec',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
