# Generated by Django 5.1.3 on 2024-11-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banani_clicker', '0005_cardholdings_cards_user_coins_per_sec_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_id', models.IntegerField()),
                ('points_to_up', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='cardholdings',
            name='card_lvl',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='lvl',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='till_next_level',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
