# Generated by Django 5.1.3 on 2024-11-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banani_clicker', '0006_level_cardholdings_card_lvl_user_lvl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='till_next_level',
            field=models.IntegerField(default=500),
        ),
    ]
