# Generated by Django 5.1.3 on 2024-11-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banani_clicker', '0007_alter_user_till_next_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.AddField(
            model_name='cards',
            name='card_lvl',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
