# Generated by Django 5.1.3 on 2024-11-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banani_clicker', '0009_alter_cardholdings_card_lvl'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardholdings',
            name='card_new_cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardholdings',
            name='card_new_pnt_per_sec',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
